baseURL = "https://boys-love.club/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "Boy's Love"
theme = "HN-hugo"
enableGitInfo = true
disableHugoGeneratorInject = true

[languages]
  [languages.zh]
    weight = 2
    languageName = "简体"
  [languages.zht]
    weight = 1
    languageName = "繁體"


[imaging]
quality = 100
